import HomeHeader from '@/layout/HomeHeader'
import './globals.css'
import {  DM_Sans } from 'next/font/google'

const dm_Sans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
  style: ["normal", "italic"],
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${dm_Sans.variable} font-dmSans text-secondary`}>{children}</body>
    </html>
  );
}
